/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uci.ics.khefner.service.idm;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        BasicService classUnderTest = new BasicService();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
